<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <GamePath Condition="'$(GamePath)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</GamePath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony" HintPath="$(GamePath)\BepInEx\core\0Harmony.dll" />
    <Reference Include="Mono.Cecil" HintPath="$(GamePath)\BepInEx\core\Mono.Cecil.dll" />
    <Reference Include="assembly_valheim" HintPath="$(GamePath)\valheim_Data\Managed\assembly_valheim.dll" Private="false" />
    <Reference Include="assembly_utils" HintPath="$(GamePath)\valheim_Data\Managed\assembly_utils.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(GamePath)\valheim_Data\Managed\UnityEngine.CoreModule.dll" Private="false" />
  </ItemGroup>
</Project>
